name: Deploy Kafka Messages to GitHub Pages

on:
  push:
    branches:
      - main
  schedule:
    - cron: "*/5 * * * *"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: pip install kafka-python

      - name: Run Kafka consumer and save messages
        run: python consumer/save_messages.py

      - name: Commit and push messages.json
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add web/messages.json
          git commit -m "Update messages.json" || echo "No changes to commit"
          git push
